<?php

/**
 * @file
 * Provides block_form functionality.
 */

/**
 * Implements hook block Info.
 * Implements hook blocks Info
 */
function block_form_block_info() {
  $blocks = array();
  $blocks['my_block'] = array(
    'info' => t('My Custom Block'),
  );
  return $blocks;
}

/**
 * Implements hook block view.
 */
function block_form_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'my_block':
      $block['subject'] = t('My Custom Block');
      $block['content'] = $block['content'] = my_block_view();
      break;
  }
  return $block;
}

/**
 * Implements myblock view function.
 */
function my_block_view() {
  $block = array(
    'image' => array(
      '#prefix' => '',
      '#type' => 'markup',
      '#markup' => 'Test my blocks',
    ),
  );
  return $block;
}
